### ISSUE TITLE
Simple Identity Server Manager Build

### ISSUE THREAD

**Issue by trix4rabbit** [thabart/SimpleIdentityServerManager#17]
After following the desktop build process, 

    Install node-webkit : npm install -g nw
    Launch the application by executing the command line : nw

the 'nw' command generates a blank screen.

Things I have tried (On Windows 7 x64 System)
1. Using NPM from node.js, the web build process fails
2. Start the Manager from source code (RC 1.0.1 & RC 1.0.2), but it returns http 404 code 
3. Started both server(5000) and manager (5001), but no manager

![simpleidentityservermanager](https://cloud.githubusercontent.com/assets/17505868/13565674/7f186636-e48c-11e5-924d-f10f8716674c.png)

**Comment by thabart** [comment]
To start the SimpleIdentityServerManager website, the two APIs "SimpleIdentityServer" & "SimpleIdentityServer.Manager.Host" needs to be started, follow to steps to run the application:
1. Follow what I have explained in the ticket : https://github.com/thabart/SimpleIdentityServer/issues/119
2. Run "SimpleIdentityServer.Startup" via the command "dnx web"
3. In "SimpleIdentityServer.Manager.Host" update the connection string
4. Run this application
5. And finally launch the website via the command : "grunt dev"

It has been a while that I didn't test the "node-webkit" feature. When i've finished with the RC2 (Docker ...), i'll include node-webkit in the RC3.

**Comment by trix4rabbit** [comment]
At this point, I think it is my npm settings / package.  I will close this ticket.  Thanks.
